
-- 配置 GEN_TABLE_CONFIG3
DROP TABLE GEN_TABLE_CONFIG3;
CREATE TABLE GEN_TABLE_CONFIG3 (
  ID NUMBER(19,0) PRIMARY KEY,
  AUTHOR VARCHAR2(255) ,
  VERSION VARCHAR2(20) DEFAULT 'V1.0' NOT NULL ENABLE,
  CAMEL_CASE VARCHAR2(1) NOT NULL,
  BASE_PACKAGE VARCHAR2(255) ,
  MODULE_NAME VARCHAR2(50) ,
--  BACK_DIR VARCHAR2(127),
--  FRONT_DIR VARCHAR2(127),
  DATABASE_ID VARCHAR2(255),
  STATUS NUMBER(1,0),
  "DESC" VARCHAR2(100),
  UPDATE_VERSION NUMBER(8,0) DEFAULT '1' NOT NULL ENABLE,
  UPDATE_TIME TIMESTAMP NOT NULL
);

COMMENT ON TABLE  GEN_TABLE_CONFIG3 IS '代码生成::配置';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.ID IS '表ID';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.AUTHOR IS '作者';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.VERSION IS '版本(v1.0)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.BASE_PACKAGE IS '包基础名称(example:com.mee.generator)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.MODULE_NAME IS '模块所在目录（example：BASE_PACKAGE.module.MODULE_NAME)';
--COMMENT ON COLUMN GEN_TABLE_CONFIG3.BACK_DIR IS '后端代码所在目录';
--COMMENT ON COLUMN GEN_TABLE_CONFIG3.FRONT_DIR IS '前端代码所在目录';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.DATABASE_ID IS '数据类型(default,mysql、postgresql、oracle等等)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.STATUS IS '状态 1.启用 0.禁用（一般至少有一个启用的）';
COMMENT ON COLUMN GEN_TABLE_CONFIG3."DESC" IS '描述';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.UPDATE_VERSION IS '更新版本';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.UPDATE_TIME IS '更新时间';

-- 表 GEN_TABLE3
DROP TABLE GEN_TABLE3;
CREATE TABLE GEN_TABLE3(
  ID NUMBER(19,0) PRIMARY KEY,
  TABLE_NAME VARCHAR2(200),
  TABLE_COMMENT VARCHAR2(500),
  CURRENT_DB VARCHAR2(50),
  DATABASE_ID VARCHAR2(50),
  CLASS_NAME VARCHAR2(127),
  BASE_PACKAGE VARCHAR2(100),
  MODULE_NAME VARCHAR2(30),
  AUTHOR VARCHAR2(50),
  VERSION VARCHAR2(50),
  CAMEL_CASE VARCHAR2(1),
--  BACK_DIR VARCHAR2(100),
--  FRONT_DIR VARCHAR2(100),
  "DESC" VARCHAR2(255),
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP NOT NULL ENABLE,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN_TABLE3 IS '代码生成::业务表';
COMMENT ON COLUMN GEN_TABLE3.ID IS 'ID';
COMMENT ON COLUMN GEN_TABLE3.TABLE_NAME IS '表名称';
COMMENT ON COLUMN GEN_TABLE3.TABLE_COMMENT IS '表描述';
COMMENT ON COLUMN GEN_TABLE3.CURRENT_DB IS '当前数据库类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN_TABLE3.DATABASE_ID IS 'DB语句类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN_TABLE3.CLASS_NAME IS '实体类名称';
COMMENT ON COLUMN GEN_TABLE3.BASE_PACKAGE IS '包基础路径';
COMMENT ON COLUMN GEN_TABLE3.MODULE_NAME IS '代码所在模块';
COMMENT ON COLUMN GEN_TABLE3.AUTHOR IS '作者';
COMMENT ON COLUMN GEN_TABLE3.VERSION IS '版本';
COMMENT ON COLUMN GEN_TABLE3.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
--COMMENT ON COLUMN GEN_TABLE3.BACK_DIR IS '下载后端代码所在文件夹';
--COMMENT ON COLUMN GEN_TABLE3.FRONT_DIR IS '下载前端代码所在文件夹';
COMMENT ON COLUMN GEN_TABLE3."DESC" IS '备注';
COMMENT ON COLUMN GEN_TABLE3.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE3.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN_TABLE3.UPDATE_BY IS '更新者';
COMMENT ON COLUMN GEN_TABLE3.UPDATE_TIME IS '更新时间';

-- 字段 GEN_TABLE_COLUMN3
DROP TABLE GEN_TABLE_COLUMN3;
CREATE TABLE GEN_TABLE_COLUMN3(
  ID NUMBER(19,0) PRIMARY KEY,
  TABLE_ID NUMBER(19,0),
  COLUMN_NAME VARCHAR2(200) ,
  COLUMN_COMMENT VARCHAR2(500) ,
  COLUMN_TYPE VARCHAR2(100) ,
  JAVA_TYPE VARCHAR2(255) ,
  JAVA_FIELD VARCHAR2(255) ,
  IS_PK VARCHAR2(1) ,
  IS_INCREMENT VARCHAR2(1) ,
  IS_REQUIRED VARCHAR2(1) ,
  IS_INSERT VARCHAR2(1) ,
  IS_EDIT VARCHAR2(1) ,
  IS_LIST VARCHAR2(1) ,
  IS_QUERY VARCHAR2(1) ,
  QUERY_TYPE VARCHAR2(20),
  HTML_TYPE VARCHAR2(200),
  DICT_TYPE VARCHAR2(200),
  SORT NUMBER(8,0),
  CREATE_BY VARCHAR2(64) NOT NULL ENABLE,
  CREATE_TIME TIMESTAMP NOT NULL ENABLE,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN_TABLE_COLUMN3 IS '代码生成::业务字段';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.ID IS '编号';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.TABLE_ID IS '归属表编号(GEN_TABLE3=>ID)';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_NAME IS '列名称';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_COMMENT IS '列描述';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_TYPE IS '列类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.JAVA_TYPE IS 'JAVA类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.JAVA_FIELD IS 'JAVA字段名';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_PK IS '是否主键（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_INCREMENT IS '是否自增（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_REQUIRED IS '是否必填（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_INSERT IS '是否为插入字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_EDIT IS '是否编辑字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_LIST IS '是否列表字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_QUERY IS '是否查询字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.QUERY_TYPE IS '查询方式（等于、不等于、大于、小于、范围）若范围会生成两个插叙字段_start、_end';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.HTML_TYPE IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.SORT IS '排序';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.UPDATE_BY IS '修改人';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.UPDATE_TIME IS '修改时间';

-- GEN_TABLE
DROP TABLE GEN_TABLE;
CREATE TABLE "GEN_TABLE" (
  TABLE_ID NUMERIC(19,0) PRIMARY KEY ,
  TABLE_NAME VARCHAR2(200),
  TABLE_COMMENT VARCHAR2(500),
  SUB_TABLE_NAME VARCHAR2(64),
  SUB_TABLE_FK_NAME VARCHAR2(64),
  CLASS_NAME VARCHAR2(100),
  TPL_CATEGORY VARCHAR2(200),
  PACKAGE_NAME VARCHAR2(100),
  MODULE_NAME VARCHAR2(30),
  BUSINESS_NAME VARCHAR2(30),
  FUNCTION_NAME VARCHAR2(50),
  FUNCTION_VERSION VARCHAR2(20) DEFAULT 'v1.0',
  FUNCTION_AUTHOR VARCHAR2(50),
  GEN_TYPE char(1),
  GEN_PATH VARCHAR2(200),
  OPTIONS VARCHAR2(1000),
  CREATE_BY VARCHAR2(64),
  CREATE_TIME timestamp(6),
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME timestamp(6),
  REMARK VARCHAR2(500)
);

COMMENT ON COLUMN GEN_TABLE.TABLE_ID IS '编号';
COMMENT ON COLUMN GEN_TABLE.TABLE_NAME IS '表名称';
COMMENT ON COLUMN GEN_TABLE.TABLE_COMMENT IS '表描述';
COMMENT ON COLUMN GEN_TABLE.SUB_TABLE_NAME IS '关联子表的表名';
COMMENT ON COLUMN GEN_TABLE.SUB_TABLE_FK_NAME IS '子表关联的外键名';
COMMENT ON COLUMN GEN_TABLE.CLASS_NAME IS '实体类名称';
COMMENT ON COLUMN GEN_TABLE.TPL_CATEGORY IS '使用的模板';
COMMENT ON COLUMN GEN_TABLE.PACKAGE_NAME IS '生成包路径';
COMMENT ON COLUMN GEN_TABLE.MODULE_NAME IS '生成模块名';
COMMENT ON COLUMN GEN_TABLE.BUSINESS_NAME IS '生成业务名';
COMMENT ON COLUMN GEN_TABLE.FUNCTION_NAME IS '生成功能名';
COMMENT ON COLUMN GEN_TABLE.FUNCTION_VERSION IS '功能版本';
COMMENT ON COLUMN GEN_TABLE.FUNCTION_AUTHOR IS '生成功能作者';
COMMENT ON COLUMN GEN_TABLE.GEN_TYPE IS '生成代码方式';
COMMENT ON COLUMN GEN_TABLE.GEN_PATH IS '生成路径';
COMMENT ON COLUMN GEN_TABLE.OPTIONS IS '其它生成选项';
COMMENT ON COLUMN GEN_TABLE.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN_TABLE.UPDATE_BY IS '更新者';
COMMENT ON COLUMN GEN_TABLE.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN GEN_TABLE.REMARK IS '备注';
COMMENT ON TABLE  GEN_TABLE IS '代码生成业务表';


DROP TABLE GEN2_TABLE;
CREATE TABLE GEN2_TABLE(
  ID NUMBER(19,0) PRIMARY KEY,
  TABLE_NAME VARCHAR2(200),
  TABLE_COMMENT VARCHAR2(500),
  CURRENT_DB VARCHAR2(50),
  DATABASE_ID VARCHAR2(50),
  CLASS_NAME VARCHAR2(127),
  BASE_PACKAGE VARCHAR2(100),
  MODULE_NAME VARCHAR2(30),
  AUTHOR VARCHAR2(50),
  VERSION VARCHAR2(50),
  CAMEL_CASE VARCHAR2(1),
  BACK_DIR VARCHAR2(100),
  FRONT_DIR VARCHAR2(100),
  "DESC" VARCHAR2(255),
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN2_TABLE IS '单体代码生成::业务表';
COMMENT ON COLUMN GEN2_TABLE.ID IS 'ID';
COMMENT ON COLUMN GEN2_TABLE.TABLE_NAME IS '表名称';
COMMENT ON COLUMN GEN2_TABLE.TABLE_COMMENT IS '表描述';
COMMENT ON COLUMN GEN2_TABLE.CURRENT_DB IS '当前数据库类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN2_TABLE.DATABASE_ID IS 'DB语句类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN2_TABLE.CLASS_NAME IS '实体类名称';
COMMENT ON COLUMN GEN2_TABLE.BASE_PACKAGE IS '包基础路径';
COMMENT ON COLUMN GEN2_TABLE.MODULE_NAME IS '代码所在模块';
COMMENT ON COLUMN GEN2_TABLE.AUTHOR IS '作者';
COMMENT ON COLUMN GEN2_TABLE.VERSION IS '版本';
COMMENT ON COLUMN GEN2_TABLE.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
COMMENT ON COLUMN GEN2_TABLE.BACK_DIR IS '下载后端代码所在文件夹';
COMMENT ON COLUMN GEN2_TABLE.FRONT_DIR IS '下载前端代码所在文件夹';

-- 配置 GEN2_CONFIG
DROP TABLE GEN2_CONFIG;
CREATE TABLE GEN2_CONFIG (
  ID NUMERIC(19,0) PRIMARY KEY,
  AUTHOR VARCHAR2(255) ,
  VERSION VARCHAR2(20) DEFAULT 'V1.0',
  CAMEL_CASE VARCHAR2(1) NOT NULL,
  BASE_PACKAGE VARCHAR2(255) ,
  MODULE_NAME VARCHAR2(50) ,
  DATABASE_ID VARCHAR2(255),
  STATUS NUMERIC(2,0),
  "DESC" VARCHAR2(100),
  UPDATE_VERSION NUMERIC(8,0)  DEFAULT '1',
  UPDATE_TIME TIMESTAMP NOT NULL
);

COMMENT ON TABLE  GEN2_CONFIG IS '单体代码生成::配置';
COMMENT ON COLUMN GEN2_CONFIG.ID IS '表ID';
COMMENT ON COLUMN GEN2_CONFIG.AUTHOR IS '作者';
COMMENT ON COLUMN GEN2_CONFIG.VERSION IS '版本(v1.0)';
COMMENT ON COLUMN GEN2_CONFIG.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
COMMENT ON COLUMN GEN2_CONFIG.BASE_PACKAGE IS '包基础名称(example:com.mee.generator)';
COMMENT ON COLUMN GEN2_CONFIG.MODULE_NAME IS '模块所在目录（example：BASE_PACKAGE.module.MODULE_NAME)';
COMMENT ON COLUMN GEN2_CONFIG.DATABASE_ID IS '数据类型(default,mysql、postgresql、oracle等等)';
COMMENT ON COLUMN GEN2_CONFIG.STATUS IS '状态 1.启用 0.禁用（一般至少有一个启用的）';
COMMENT ON COLUMN GEN2_CONFIG."DESC" IS '描述';
COMMENT ON COLUMN GEN2_CONFIG.UPDATE_VERSION IS '更新版本';
COMMENT ON COLUMN GEN2_CONFIG.UPDATE_TIME IS '更新时间';


-- 字段 GEN_TABLE_COLUMN
DROP TABLE GEN2_COLUMN;
CREATE TABLE GEN2_COLUMN(
    ID NUMBER(19,0) PRIMARY KEY,
    TABLE_ID NUMBER(19,0),
    COLUMN_NAME VARCHAR(200) ,
    COLUMN_COMMENT VARCHAR(500) ,
    COLUMN_TYPE VARCHAR(100) ,
    JAVA_TYPE VARCHAR(255) ,
    JAVA_FIELD VARCHAR(255) ,
    IS_PK VARCHAR(1) ,
    IS_INCREMENT VARCHAR(1) ,
    IS_REQUIRED VARCHAR(1) ,
    IS_INSERT VARCHAR(1) ,
    IS_EDIT VARCHAR(1) ,
    IS_LIST VARCHAR(1) ,
    IS_QUERY VARCHAR(1) ,
    QUERY_TYPE VARCHAR(200) DEFAULT 'EQ',
    HTML_TYPE VARCHAR(200),
    DICT_TYPE VARCHAR(200),
    SORT NUMBER(8,0),
    CREATE_BY VARCHAR(64) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN2_COLUMN IS '单体代码生成::业务字段';
COMMENT ON COLUMN GEN2_COLUMN.ID IS '编号';
COMMENT ON COLUMN GEN2_COLUMN.TABLE_ID IS '归属表编号(GEN2_TABLE=>ID)';
COMMENT ON COLUMN GEN2_COLUMN.COLUMN_NAME IS '列名称';
COMMENT ON COLUMN GEN2_COLUMN.COLUMN_COMMENT IS '列描述';
COMMENT ON COLUMN GEN2_COLUMN.COLUMN_TYPE IS '列类型';
COMMENT ON COLUMN GEN2_COLUMN.JAVA_TYPE IS 'JAVA类型';
COMMENT ON COLUMN GEN2_COLUMN.JAVA_FIELD IS 'JAVA字段名';
COMMENT ON COLUMN GEN2_COLUMN.IS_PK IS '是否主键（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_INCREMENT IS '是否自增（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_REQUIRED IS '是否必填（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_INSERT IS '是否为插入字段（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_EDIT IS '是否编辑字段（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_LIST IS '是否列表字段（1是）';
COMMENT ON COLUMN GEN2_COLUMN.IS_QUERY IS '是否查询字段（1是）';
COMMENT ON COLUMN GEN2_COLUMN.QUERY_TYPE IS '查询方式（等于、不等于、大于、小于、范围）若范围会生成两个插叙字段_start、_end';
COMMENT ON COLUMN GEN2_COLUMN.HTML_TYPE IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN GEN2_COLUMN.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN GEN2_COLUMN.SORT IS '排序';
COMMENT ON COLUMN GEN2_COLUMN.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN2_COLUMN.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN2_COLUMN.UPDATE_BY IS '修改人';
COMMENT ON COLUMN GEN2_COLUMN.UPDATE_TIME IS '修改时间';

DROP TABLE GEN_TABLE_COLUMN;
CREATE TABLE GEN_TABLE_COLUMN (
  COLUMN_ID NUMBER(19,0) primary key,
  TABLE_ID NUMBER(19,0),
  COLUMN_NAME VARCHAR2(200),
  COLUMN_COMMENT VARCHAR2(500),
  COLUMN_TYPE VARCHAR2(100),
  JAVA_TYPE VARCHAR2(500),
  JAVA_FIELD VARCHAR2(200),
  IS_PK VARCHAR2(1),
  IS_INCREMENT VARCHAR2(1),
  IS_REQUIRED VARCHAR2(1),
  IS_INSERT VARCHAR2(1),
  IS_EDIT VARCHAR2(1),
  IS_LIST VARCHAR2(1),
  IS_QUERY VARCHAR2(1),
  QUERY_TYPE VARCHAR2(200) DEFAULT 'EQ',
  HTML_TYPE VARCHAR2(200),
  DICT_TYPE VARCHAR2(200) DEFAULT '',
  SORT NUMBER(8,0),
  CREATE_BY VARCHAR2(64) DEFAULT '',
  CREATE_TIME timestamp
);

COMMENT ON COLUMN GEN_TABLE_COLUMN.COLUMN_ID IS '编号';
COMMENT ON COLUMN GEN_TABLE_COLUMN.TABLE_ID IS '归属表编号';
COMMENT ON COLUMN GEN_TABLE_COLUMN.COLUMN_NAME IS '列名称';
COMMENT ON COLUMN GEN_TABLE_COLUMN.COLUMN_COMMENT IS '列描述';
COMMENT ON COLUMN GEN_TABLE_COLUMN.COLUMN_TYPE IS '列类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN.JAVA_TYPE IS 'JAVA类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN.JAVA_FIELD IS 'JAVA字段名';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_PK IS '是否主键（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_INCREMENT IS '是否自增（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_REQUIRED IS '是否必填（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_INSERT IS '是否为插入字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_EDIT IS '是否编辑字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_LIST IS '是否列表字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_QUERY IS '是否查询字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.QUERY_TYPE IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.HTML_TYPE IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN GEN_TABLE_COLUMN.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN.SORT IS '排序';
COMMENT ON COLUMN GEN_TABLE_COLUMN.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE_COLUMN.CREATE_TIME IS '创建时间';
COMMENT ON TABLE  GEN_TABLE_COLUMN IS '代码生成业务表字段';
