
-- 配置 GEN_TABLE_CONFIG3
DROP TABLE GEN_TABLE_CONFIG3;
CREATE TABLE GEN_TABLE_CONFIG3 (
  ID NUMBER(19,0) PRIMARY KEY,
  AUTHOR VARCHAR2(255) ,
  VERSION VARCHAR2(20) DEFAULT 'V1.0' NOT NULL ENABLE,
  CAMEL_CASE VARCHAR2(1) NOT NULL,
  BASE_PACKAGE VARCHAR2(255) ,
  MODULE_NAME VARCHAR2(50) ,
  BACK_DIR VARCHAR2(127),
  FRONT_DIR VARCHAR2(127),
  DATABASE_ID VARCHAR2(255),
  STATUS NUMBER(1,0),
  "DESC" VARCHAR2(100),
  UPDATE_VERSION NUMBER(8,0) DEFAULT '1' NOT NULL ENABLE,
  UPDATE_TIME TIMESTAMP NOT NULL
);

COMMENT ON TABLE  GEN_TABLE_CONFIG3 IS '代码生成::配置';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.ID IS '表ID';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.AUTHOR IS '作者';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.VERSION IS '版本(v1.0)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.BASE_PACKAGE IS '包基础名称(example:com.mee.generator)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.MODULE_NAME IS '模块所在目录（example：BASE_PACKAGE.module.MODULE_NAME)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.BACK_DIR IS '后端代码所在目录';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.FRONT_DIR IS '前端代码所在目录';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.DATABASE_ID IS '数据类型(default,mysql、postgresql、oracle等等)';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.STATUS IS '状态 1.启用 0.禁用（一般至少有一个启用的）';
COMMENT ON COLUMN GEN_TABLE_CONFIG3."DESC" IS '描述';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.UPDATE_VERSION IS '更新版本';
COMMENT ON COLUMN GEN_TABLE_CONFIG3.UPDATE_TIME IS '更新时间';

-- 表 GEN_TABLE3
DROP TABLE GEN_TABLE3;
CREATE TABLE GEN_TABLE3(
  ID NUMBER(19,0) PRIMARY KEY,
  TABLE_NAME VARCHAR2(200),
  TABLE_COMMENT VARCHAR2(500),
  CURRENT_DB VARCHAR2(50),
  DATABASE_ID VARCHAR2(50),
  CLASS_NAME VARCHAR2(127),
  BASE_PACKAGE VARCHAR2(100),
  MODULE_NAME VARCHAR2(30),
  AUTHOR VARCHAR2(50),
  VERSION VARCHAR2(50),
  CAMEL_CASE VARCHAR2(1),
  BACK_DIR VARCHAR2(100),
  FRONT_DIR VARCHAR2(100),
  "DESC" VARCHAR2(255),
  CREATE_BY VARCHAR2(64),
  CREATE_TIME TIMESTAMP NOT NULL ENABLE,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN_TABLE3 IS '代码生成::业务表';
COMMENT ON COLUMN GEN_TABLE3.ID IS 'ID';
COMMENT ON COLUMN GEN_TABLE3.TABLE_NAME IS '表名称';
COMMENT ON COLUMN GEN_TABLE3.TABLE_COMMENT IS '表描述';
COMMENT ON COLUMN GEN_TABLE3.CURRENT_DB IS '当前数据库类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN_TABLE3.DATABASE_ID IS 'DB语句类型(mysql、oracle、postgresql)';
COMMENT ON COLUMN GEN_TABLE3.CLASS_NAME IS '实体类名称';
COMMENT ON COLUMN GEN_TABLE3.BASE_PACKAGE IS '包基础路径';
COMMENT ON COLUMN GEN_TABLE3.MODULE_NAME IS '代码所在模块';
COMMENT ON COLUMN GEN_TABLE3.AUTHOR IS '作者';
COMMENT ON COLUMN GEN_TABLE3.VERSION IS '版本';
COMMENT ON COLUMN GEN_TABLE3.CAMEL_CASE IS '接口、字段是否驼峰格式 1.是 0.否';
COMMENT ON COLUMN GEN_TABLE3.BACK_DIR IS '下载后端代码所在文件夹';
COMMENT ON COLUMN GEN_TABLE3.FRONT_DIR IS '下载前端代码所在文件夹';
COMMENT ON COLUMN GEN_TABLE3."DESC" IS '备注';
COMMENT ON COLUMN GEN_TABLE3.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE3.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN_TABLE3.UPDATE_BY IS '更新者';
COMMENT ON COLUMN GEN_TABLE3.UPDATE_TIME IS '更新时间';

-- 字段 GEN_TABLE_COLUMN3
DROP TABLE GEN_TABLE_COLUMN3;
CREATE TABLE GEN_TABLE_COLUMN3(
  ID NUMBER(19,0) PRIMARY KEY,
  TABLE_ID NUMBER(19,0),
  COLUMN_NAME VARCHAR2(200) ,
  COLUMN_COMMENT VARCHAR2(500) ,
  COLUMN_TYPE VARCHAR2(100) ,
  JAVA_TYPE VARCHAR2(255) ,
  JAVA_FIELD VARCHAR2(255) ,
  IS_PK VARCHAR2(1) ,
  IS_INCREMENT VARCHAR2(1) ,
  IS_REQUIRED VARCHAR2(1) ,
  IS_INSERT VARCHAR2(1) ,
  IS_EDIT VARCHAR2(1) ,
  IS_LIST VARCHAR2(1) ,
  IS_QUERY VARCHAR2(1) ,
  QUERY_TYPE VARCHAR2(200) DEFAULT 'EQ' NOT NULL ENABLE,
  HTML_TYPE VARCHAR2(200),
  DICT_TYPE VARCHAR2(200),
  SORT NUMBER(8,0),
  CREATE_BY VARCHAR2(64) NOT NULL ENABLE,
  CREATE_TIME TIMESTAMP NOT NULL ENABLE,
  UPDATE_BY VARCHAR2(64),
  UPDATE_TIME TIMESTAMP
);

COMMENT ON TABLE  GEN_TABLE_COLUMN3 IS '代码生成::业务字段';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.ID IS '编号';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.TABLE_ID IS '归属表编号(GEN_TABLE3=>ID)';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_NAME IS '列名称';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_COMMENT IS '列描述';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.COLUMN_TYPE IS '列类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.JAVA_TYPE IS 'JAVA类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.JAVA_FIELD IS 'JAVA字段名';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_PK IS '是否主键（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_INCREMENT IS '是否自增（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_REQUIRED IS '是否必填（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_INSERT IS '是否为插入字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_EDIT IS '是否编辑字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_LIST IS '是否列表字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.IS_QUERY IS '是否查询字段（1是）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.QUERY_TYPE IS '查询方式（等于、不等于、大于、小于、范围）若范围会生成两个插叙字段_start、_end';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.HTML_TYPE IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.DICT_TYPE IS '字典类型';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.SORT IS '排序';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.CREATE_BY IS '创建者';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.UPDATE_BY IS '修改人';
COMMENT ON COLUMN GEN_TABLE_COLUMN3.UPDATE_TIME IS '修改时间';

